# https://pre-commit.com/hooks.html
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: no-commit-to-branch
  - id: check-yaml
    args: ['--unsafe']
  - id: end-of-file-fixer
  - id: trailing-whitespace

# Code formatting through black
- repo: https://github.com/psf/black
  rev: 25.1.0
  hooks:
  - id: black-jupyter
    name: Uncompromising Python Code Formater

# Fast Linting through ruff
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.10
  hooks:
  - id: ruff
    name: Package Formatting
    args: ['--fix-only']
