blank_issues_enabled: false
# contact_links:
#   - name: 🤔 Ask a Question
#     url: 'https://github.com/Mermeid-Designs/single-repo-python/discussions/new?category=question'  # TODO: adjust the repo name
#     about: Ask a question about how to use the data library using github discussions
