name: PR Assignee Management

on:
  pull_request:
    types: [opened, synchronize, edited, ready_for_review]

jobs:
  main:
    name: Automatically add assignees on PRs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Edit pull request
        env:
          GH_TOKEN: ${{ github.token }}
          GITHUB_USER: ${{ github.actor }}
          PR_NUMBER: ${{ github.event.number }}
          THIS_REPO: ${{ github.repository }}
        run: |
          pushd ${THIS_REPO}
          gh pr edit ${PR_NUMBER} \
            --add-assignee ${GITHUB_USER}
          popd
