name: Set PR reviewers and assignees

on:
  pull_request:
    types: [ready_for_review]

env:
  BASE_BRANCH: main
  GIT_AUTHOR_NAME: ${{ github.repository_owner }}
  GIT_AUTHOR_EMAIL: ${{ github.repository_owner }}@users.noreply.github.com
  THIS_REPO: ${{ github.repository }}
  PR_NUMBER: ${{ github.event.number }}


jobs:
  reviewers:
    name: Automatically set reviewers and assignees
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v4
      - name: Edit pull request
        env:
          GH_TOKEN: ${{ github.token }}
          GITHUB_USER: ${{ github.actor }}
        run: |
          pushd ${THIS_REPO}
          gh pr edit ${PR_NUMBER} \
            --add-assignee ${GITHUB_USER}
            # --add-reviewer 
          popd